//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommunityDevelopers2ISAWinForm.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CommunityDevelopers2ISAWinForm.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ajouter {
            get {
                object obj = ResourceManager.GetObject("ajouter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ajouter_un_message {
            get {
                object obj = ResourceManager.GetObject("ajouter_un_message", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap annuler_icone_8717_32 {
            get {
                object obj = ResourceManager.GetObject("annuler_icone_8717_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ConnexionForm {
            get {
                object obj = ResourceManager.GetObject("ConnexionForm", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Continuity_Discussion_forum_logo {
            get {
                object obj = ResourceManager.GetObject("Continuity_Discussion_forum_logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap edit {
            get {
                object obj = ResourceManager.GetObject("edit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap edit_sujet {
            get {
                object obj = ResourceManager.GetObject("edit_sujet", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap forum_discussion {
            get {
                object obj = ResourceManager.GetObject("forum_discussion", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap login {
            get {
                object obj = ResourceManager.GetObject("login", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap logout {
            get {
                object obj = ResourceManager.GetObject("logout", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap message_supprimez {
            get {
                object obj = ResourceManager.GetObject("message_supprimez", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ModifierMdp {
            get {
                object obj = ResourceManager.GetObject("ModifierMdp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à la réponse a été ajouter avec succès.
        /// </summary>
        internal static string MsgBoxAddReponseText {
            get {
                return ResourceManager.GetString("MsgBoxAddReponseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ajouter une réponse.
        /// </summary>
        internal static string MsgBoxAddReponseTitre {
            get {
                return ResourceManager.GetString("MsgBoxAddReponseTitre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le sujet a été ajouté avec succès.
        /// </summary>
        internal static string MsgBoxAddSujetText {
            get {
                return ResourceManager.GetString("MsgBoxAddSujetText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ajouter un sujet.
        /// </summary>
        internal static string MsgBoxAddSujetTitre {
            get {
                return ResourceManager.GetString("MsgBoxAddSujetTitre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Etes-vous sur de vouloir quitter ? Si oui les modifications éffectuées ne seront pas prises en compte..
        /// </summary>
        internal static string MsgBoxCancelText {
            get {
                return ResourceManager.GetString("MsgBoxCancelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Annuler.
        /// </summary>
        internal static string MsgBoxCancelTitre {
            get {
                return ResourceManager.GetString("MsgBoxCancelTitre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Etes-vous sur vouloir changer votre password.
        /// </summary>
        internal static string MsgBoxConfirmChangementPasswordText {
            get {
                return ResourceManager.GetString("MsgBoxConfirmChangementPasswordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Confirmer changement password.
        /// </summary>
        internal static string MsgBoxConfirmChangementPasswordTitre {
            get {
                return ResourceManager.GetString("MsgBoxConfirmChangementPasswordTitre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vous-êtes déconnecté, avec succès.
        /// </summary>
        internal static string MsgBoxDeconnexionText {
            get {
                return ResourceManager.GetString("MsgBoxDeconnexionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Déconnexion.
        /// </summary>
        internal static string MsgBoxDeconnexionTitre {
            get {
                return ResourceManager.GetString("MsgBoxDeconnexionTitre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Etes-vous sur de vouloir supprimer la réponse ?.
        /// </summary>
        internal static string MsgBoxDeletePostText {
            get {
                return ResourceManager.GetString("MsgBoxDeletePostText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Suppression de la réponse.
        /// </summary>
        internal static string MsgBoxDeletePostTitre {
            get {
                return ResourceManager.GetString("MsgBoxDeletePostTitre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Etes-vous sur de vouloir supprimer le sujet sélectionné ?.
        /// </summary>
        internal static string MsgBoxDeleteSujetText {
            get {
                return ResourceManager.GetString("MsgBoxDeleteSujetText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Suppression du Sujet.
        /// </summary>
        internal static string MsgBoxDeleteSujetTitre {
            get {
                return ResourceManager.GetString("MsgBoxDeleteSujetTitre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le sujet a été modifié avec succès.
        /// </summary>
        internal static string MsgBoxEditSujetText {
            get {
                return ResourceManager.GetString("MsgBoxEditSujetText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Modification du sujet.
        /// </summary>
        internal static string MsgBoxEditSujetTitre {
            get {
                return ResourceManager.GetString("MsgBoxEditSujetTitre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Impossible d&apos;ajouter la réponse !.
        /// </summary>
        internal static string MsgBoxErreurAddReponseText {
            get {
                return ResourceManager.GetString("MsgBoxErreurAddReponseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur au moment de l&apos;ajout de la réponse.
        /// </summary>
        internal static string MsgBoxErreurAddReponseTitre {
            get {
                return ResourceManager.GetString("MsgBoxErreurAddReponseTitre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Impossible d&apos;ajouter le sujet.
        /// </summary>
        internal static string MsgBoxErreurAddSujetText {
            get {
                return ResourceManager.GetString("MsgBoxErreurAddSujetText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur au moment de l&apos;ajout du sujet.
        /// </summary>
        internal static string MsgBoxErreurAddSujetTitre {
            get {
                return ResourceManager.GetString("MsgBoxErreurAddSujetTitre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Suppression impossible de la réponse !.
        /// </summary>
        internal static string MsgBoxErreurDeletePostText {
            get {
                return ResourceManager.GetString("MsgBoxErreurDeletePostText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur !.
        /// </summary>
        internal static string MsgBoxErreurDeletePostTitre {
            get {
                return ResourceManager.GetString("MsgBoxErreurDeletePostTitre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Suppression impossible du sujet !.
        /// </summary>
        internal static string MsgBoxErreurDeleteSujetText {
            get {
                return ResourceManager.GetString("MsgBoxErreurDeleteSujetText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur !.
        /// </summary>
        internal static string MsgBoxErreurDeleteSujetTitre {
            get {
                return ResourceManager.GetString("MsgBoxErreurDeleteSujetTitre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le sujet n&apos;a pas été modifié, une erreur s&apos;est produite lors de la modification.
        /// </summary>
        internal static string MsgBoxErreurEditSujetText {
            get {
                return ResourceManager.GetString("MsgBoxErreurEditSujetText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur.
        /// </summary>
        internal static string MsgBoxErreurEditSujetTitre {
            get {
                return ResourceManager.GetString("MsgBoxErreurEditSujetTitre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le password de confirmation est différent du nouveau password saisie.
        /// </summary>
        internal static string MsgBoxErreurNewPasswordText {
            get {
                return ResourceManager.GetString("MsgBoxErreurNewPasswordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur de saisie du password.
        /// </summary>
        internal static string MsgBoxErreurNewPasswordTitre {
            get {
                return ResourceManager.GetString("MsgBoxErreurNewPasswordTitre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Etes-vous sur de vouloir modifier le sujet ?.
        /// </summary>
        internal static string MsgBoxUpDateSujetText {
            get {
                return ResourceManager.GetString("MsgBoxUpDateSujetText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mofdification du sujet.
        /// </summary>
        internal static string MsgBoxUpDateSujetTitre {
            get {
                return ResourceManager.GetString("MsgBoxUpDateSujetTitre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Désolé ! Le sujet sélectionné, ne contient aucune reponse.
        /// </summary>
        internal static string MsglblPasDeReponseText {
            get {
                return ResourceManager.GetString("MsglblPasDeReponseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pas de reponse pour le sujet sélectionné.
        /// </summary>
        internal static string MsglblPasDeReponseTitre {
            get {
                return ResourceManager.GetString("MsglblPasDeReponseTitre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Désolé ! la catégorie sélectionnée ne contient aucun sujet.
        /// </summary>
        internal static string MsglblPasDeSujetText {
            get {
                return ResourceManager.GetString("MsglblPasDeSujetText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pas de sujet pour la catégorie sélectionnée.
        /// </summary>
        internal static string MsglblPasDeSujetTitre {
            get {
                return ResourceManager.GetString("MsglblPasDeSujetTitre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap quitte {
            get {
                object obj = ResourceManager.GetObject("quitte", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap quitter {
            get {
                object obj = ResourceManager.GetObject("quitter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap reseau_recevoir_transmettre_icone_8164_32 {
            get {
                object obj = ResourceManager.GetObject("reseau_recevoir_transmettre_icone_8164_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap supprimer {
            get {
                object obj = ResourceManager.GetObject("supprimer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap validation {
            get {
                object obj = ResourceManager.GetObject("validation", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
